### ISSUE TITLE
--sample-config success, then ends with crash

### ISSUE THREAD

**Issue by robert-wallis** [WhiteHalmos/emailer#13]
Running `email --sample-config` writes a sample config, then crashes something like this:

```
...
  },
  "keys": {
    "testkey": "1PAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9I"
  },
  "serialized_creds": {
    "_comment": "This gets populated programatically"
  }
}
Traceback (most recent call last):
  File "/usr/local/bin/email", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/emailer/shell.py", line 53, in main
    config_obj, creds = get_config_and_creds(options.config_dir)
  File "/usr/local/lib/python3.7/site-packages/emailer/shell.py", line 35, in get_config_and_creds
    config_obj = config.load_from_file(config_path)
  File "/usr/local/lib/python3.7/site-packages/emailer/config.py", line 81, in load_from_file
    raise InvalidFileError(config_path)
emailer.config.InvalidFileError: None
```

Trying to get it set up in the next 30 min so I probably won't debug this right now.  Just logging the issue.

**Comment by robert-wallis** [comment]
Using docker `python:alpine` environment (3.7)

**Comment by WhiteHalmos** [comment]
Ah... this happens when there is no config file to load at all. Now to fix it without introducing unnecessary conditionals in `shell.py` :/
