### ISSUE TITLE
Catch API Error and retry

### ISSUE THREAD

**Issue by WhiteHalmos** [WhiteHalmos/emailer#9]
Traceback (most recent call last):
  File "/home/user/.virtualenvs/emailer/bin/email", line 11, in <module>
    sys.exit(main())
  File "/home/user/.virtualenvs/emailer/lib/python3.5/site-packages/emailer/main.py", line 275, in main
    run(types, today, config, skip_send=options.skip_send)
  File "/home/user/.virtualenvs/emailer/lib/python3.5/site-packages/emailer/main.py", line 210, in run
    for key in keys]
  File "/home/user/.virtualenvs/emailer/lib/python3.5/site-packages/emailer/main.py", line 210, in <listcomp>
    for key in keys]
  File "/home/user/.virtualenvs/emailer/lib/python3.5/site-packages/emailer/data.py", line 43, in __init__
    people_sheet = self.spreadsheet.worksheet('People')
  File "/home/user/.virtualenvs/emailer/lib/python3.5/site-packages/gspread/models.py", line 172, in worksheet
    sheet_data = self.fetch_sheet_metadata()
  File "/home/user/.virtualenvs/emailer/lib/python3.5/site-packages/gspread/models.py", line 123, in fetch_sheet_metadata
    r = self.client.request('get', url, params=params)
  File "/home/user/.virtualenvs/emailer/lib/python3.5/site-packages/gspread/client.py", line 79, in request
    raise APIError(response)
gspread.exceptions.APIError: {
  "error": {
    "code": 503,
    "message": "The service is currently unavailable.",
    "status": "UNAVAILABLE"
  }
}

**Comment by WaffleLover123** [comment]
Hi, I see that you managed to fix this issue and I am having the same issue. Do you mind telling me how you managed to catch that error and retry?

**Comment by WhiteHalmos** [comment]
This is popping up again.

**Comment by WhiteHalmos** [comment]
```
Traceback (most recent call last):
  File "/home/wnwen/bin/emailer/bin/email", line 10, in <module>
    sys.exit(main())
  File "/home/wnwen/bin/emailer/lib/python3.7/site-packages/emailer/main.py", line 21, in main
    skip=options.skip_send)
  File "/home/wnwen/bin/emailer/lib/python3.7/site-packages/emailer/shell.py", line 43, in process_sheets
    data = fetcher.values(sheet_id, api.sheets(config_obj.creds))
  File "/home/wnwen/bin/emailer/lib/python3.7/site-packages/emailer/fetcher.py", line 4, in values
    spreadsheetId=sheet_id, fields='sheets.properties.title').execute()
  File "/home/wnwen/bin/emailer/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/wnwen/bin/emailer/lib/python3.7/site-packages/googleapiclient/http.py", line 846, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "/home/wnwen/bin/emailer/lib/python3.7/site-packages/googleapiclient/http.py", line 183, in _retry_request
    raise exception
  File "/home/wnwen/bin/emailer/lib/python3.7/site-packages/googleapiclient/http.py", line 164, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/home/wnwen/bin/emailer/lib/python3.7/site-packages/google_auth_httplib2.py", line 223, in request
    **kwargs)
  File "/home/wnwen/bin/emailer/lib/python3.7/site-packages/google_auth_httplib2.py", line 198, in request
    uri, method, body=body, headers=request_headers, **kwargs)
  File "/home/wnwen/bin/emailer/lib/python3.7/site-packages/httplib2/__init__.py", line 1926, in request
    cachekey,
  File "/home/wnwen/bin/emailer/lib/python3.7/site-packages/httplib2/__init__.py", line 1595, in _request
    conn, request_uri, method, body, headers
  File "/home/wnwen/bin/emailer/lib/python3.7/site-packages/httplib2/__init__.py", line 1533, in _conn_request
    response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
```
